apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      name: pymol
  selector:
    {{ .Release.Name }}
