apiVersion: v1
kind: Service
metadata:
  name: pymol-app
  labels:
    app: pymol-app
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      name: {{ .Values.service.name }}
    - port: 8080
      name: signalling
      targetPort: 8080
  selector:
    app: pymol-app
